CONFIG_STDOUT_CONSOLE=y
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_SPI=y
CONFIG_SENSOR=y
CONFIG_ADXL345=y
CONFIG_I2C=y
CONFIG_GPIO=y

CONFIG_PRINTK=y
CONFIG_IPM=y
CONFIG_TIMESLICE_SIZE=1
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_HEAP_MEM_POOL_SIZE=8192
CONFIG_OPENAMP=y
CONFIG_OPENAMP_SLAVE=y
#CONFIG_OPENAMP_RSC_TABLE=y
#CONFIG_OPENAMP_RSC_TABLE_NUM_RPMSG_BUFF=8

#CONFIG_SYS_HEAP_RUNTIME_STATS=y



